### ISSUE TITLE
multi-building select does not work

### ISSUE THREAD

**Issue by andy5995** [virtushda/EgyptRemasterSource#1]
The git version of MG supports the ability to select multiple buildings that are of the same type, the same way mobile units are handled.

This is not working when playing the egypt remaster faction.

**Comment by virtushda** [comment]
There may be a needed XML tag. When 3.13 comes out, I'll provide an update if necessary.

**Comment by andy5995** [comment]
I asked Jammy about it:
```

Jammyjamjamman> <multi-selection value="true"/>
<Jammyjamjamman> there
<Jammyjamjamman> copy that into every building
<Jammyjamjamman> withing <unit><parameters>

```

**Comment by virtushda** [comment]
Tested and it doesn't crash with 3.12 so I'll add it now.

**Comment by virtushda** [comment]
Done, closing issue. Thanks for your help.

**Comment by andy5995** [comment]
You're welcome. I may be able to help in the form of pull requests. If you think of any issues that might be done by other people, please open a few github tickets; I am subscribed to both of the egypt_remaster github repos.

In fact, I would have tried this ticket, but was going to wait a few days. :)

**Comment by virtushda** [comment]
Thanks, but I'm one more sound update away from being 100% done with this mod. There's nothing else to do. In fact I've already diverted most of my modding time to the Dark Magic update.
